let objdata = [
  {
    id: "1688",
    name: "Chaitanya Food Court",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "4",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "1689",
    name: "KFC",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "4.5",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "1690",
    name: "NAWABS",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "4.5",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "1691",
    name: "Paradise",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "4.5",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "1692",
    name: "PIZZA HUT",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "4",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "1693",
    name: "BANDODU PULLAV",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "4.5",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "1694",
    name: "shadab",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "3.8",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "1695",
    name: "GOKUL",
    cloudinaryImageId: "y4nzvmpofaplssjzpghf",
    locality: "Kukatpally",
    areaName: "Kukatpally",
    costForTwo: "₹600 for two",
    cuisines: ["Biryani", "Chinese", "Andhra", "North Indian"],
    avgRating: 4.5,
    parentId: "1865",
    avgRatingString: "4.6",
    totalRatingsString: "251K+",
    sla: {
      deliveryTime: 13,
      lastMileTravel: 1.1,
      serviceability: "SERVICEABLE",
      slaString: "10-15 mins",
      lastMileTravelString: "1.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
];

export default objdata;
